# Generated by Django 3.2 on 2023-12-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_gamer_gamercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gacha.cardtype', verbose_name='Тип'),
        ),
    ]
