# Generated by Django 3.2 on 2024-05-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0003_auto_20231228_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1000, verbose_name='цена')),
                ('discountPrice', models.IntegerField(default=0, verbose_name='цена по скидке')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.card', verbose_name='карта')),
            ],
        ),
    ]
